# These are supported funding model platforms

# GitHub Sponsors (0% fees - recommended!)
# Uncomment and add your GitHub username once you enable GitHub Sponsors:
# github: chrisroge

# Ko-fi (0% fees on free tier, or $12/month for Ko-fi Gold)
# Uncomment and add your Ko-fi username once you create an account at ko-fi.com:
# ko_fi: your-username

# Buy Me a Coffee (5% fee)
# Uncomment and add your link once you create an account at buymeacoffee.com:
# custom: ["https://buymeacoffee.com/your-username"]

# Instructions:
# 1. Set up GitHub Sponsors: https://github.com/sponsors
# 2. (Optional) Create Ko-fi account: https://ko-fi.com
# 3. (Optional) Create Buy Me a Coffee: https://buymeacoffee.com
# 4. Uncomment the relevant lines above and add your usernames
# 5. Commit and push - the "Sponsor" button will appear on your repo!
