name: Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering for testing

permissions:
  contents: write  # Required to upload release assets

jobs:
  build:
    name: Build Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc

      - name: Build release binary
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Rename binary with descriptive name
        run: |
          Copy-Item target/x86_64-pc-windows-msvc/release/quindar_api.exe quindar-tone-api-windows-x64.exe
        shell: pwsh

      - name: Upload binary to release
        run: |
          gh release upload ${{ github.event.release.tag_name || github.ref_name }} quindar-tone-api-windows-x64.exe --clobber
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: quindar-tone-api-windows-x64
          path: quindar-tone-api-windows-x64.exe
