name: Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:  # Allow manual triggering for testing

permissions:
  contents: write  # Required to upload release assets

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux build (x86_64 only - no ARM cross-compile)
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            artifact_name: quindar_api
            asset_name: quindar-tone-api-linux-x86_64

          # macOS builds (both Intel and Apple Silicon)
          - target: x86_64-apple-darwin
            os: macos-13  # Intel Mac
            artifact_name: quindar_api
            asset_name: quindar-tone-api-macos-x86_64

          - target: aarch64-apple-darwin
            os: macos-14  # Apple Silicon Mac
            artifact_name: quindar_api
            asset_name: quindar-tone-api-macos-aarch64

          # Windows build
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            artifact_name: quindar_api.exe
            asset_name: quindar-tone-api-windows-x86_64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install ALSA development libraries (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev pkg-config libssl-dev

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Unix)
        if: runner.os != 'Windows'
        run: |
          strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }} || true

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
